"""
LangGraph state definition for the interview multi-agent system.
"""
from typing import TypedDict, Optional, List, Annotated, Dict
import operator


class Message(TypedDict):
    role: str        # "ai" | "human"
    content: str
    question_id: Optional[str]
    timestamp: Optional[str]


class QuestionRecord(TypedDict):
    question_id: str
    question_text: str
    question_type: str
    category: str
    difficulty: str
    is_follow_up: bool
    answer_text: Optional[str]
    score: Optional[float]
    strengths: Optional[List[str]]
    improvements: Optional[List[str]]
    # Per-answer dimension scores (stored from evaluation)
    technical_score: Optional[float]
    communication_score: Optional[float]
    confidence_score: Optional[float]
    grammar_score: Optional[float]
    time_taken_seconds: Optional[int]


class ScoreBreakdown(TypedDict):
    technical: float
    communication: float
    confidence: float
    problem_solving: float
    code_quality: float
    grammar: float


class InterviewAgentState(TypedDict):
    # Session identity
    session_id: str
    user_id: str

    # Configuration
    job_role: str
    experience_level: str
    difficulty: str
    interview_type: str
    duration_minutes: int
    company_name: Optional[str]
    personality: str

    # Resume context
    resume_text: Optional[str]
    resume_skills: Optional[List[str]]
    resume_projects: Optional[List[str]]
    resume_experience: Optional[List[str]]
    resume_certifications: Optional[List[str]]   # added — returned by resume_context_agent

    # Conversation state
    messages: Annotated[List[Message], operator.add]
    questions_asked: List[QuestionRecord]
    asked_question_texts: List[str]   # for dedup
    current_question: Optional[str]
    current_question_id: Optional[str]
    current_question_type: Optional[str]
    current_category: Optional[str]
    awaiting_answer: bool

    # Adaptive difficulty tracking
    current_difficulty: str
    consecutive_strong: int
    consecutive_weak: int
    follow_up_count: int
    max_follow_ups: int

    # Interview progress — time-aware
    question_number: int
    max_questions: int                      # kept for backward compat, now soft limit
    time_budget_seconds: int                # total interview time in seconds
    session_start_time: Optional[float]     # unix timestamp of interview start
    elapsed_seconds: float                  # seconds elapsed since start
    avg_answer_duration_seconds: float      # rolling avg of how long answers take
    remaining_time_seconds: float           # estimated time left

    # Topic coverage map for smart memory
    topic_coverage: Dict[str, int]          # {topic: times_asked}

    # Interview plan (generated by interview_planner_agent at session start)
    interview_plan: Optional[List[dict]]    # [{topic, time_allocation_seconds, priority}]

    total_score_so_far: float
    scores: List[float]

    # Current evaluation result
    last_evaluation: Optional[dict]

    # Aggregated scores
    score_breakdown: Optional[ScoreBreakdown]

    proctoring_violations: Optional[List[Dict]]

    # Status
    is_complete: bool
    end_reason: Optional[str]   # "max_questions" | "time_up" | "user_ended"

    # Next action routing
    next_action: Optional[str]  # "ask_question" | "evaluate" | "follow_up" | "end"

    # Errors
    error: Optional[str]
